# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YWMGitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YWMGitDemo
  pod 'AFNetworking', '~> 4.0.1'
  pod 'MJExtension', '~> 3.2.2'
  
end
